
import React from 'react';

interface TermsOfServiceModalProps {
    onAccept: () => void;
}

const TermsOfServiceModal: React.FC<TermsOfServiceModalProps> = ({ onAccept }) => {
    return (
        <div className="fixed inset-0 bg-black bg-opacity-75 z-50 flex items-center justify-center p-4">
            <div className="bg-light-bg dark:bg-dark-sidebar rounded-lg shadow-xl w-full max-w-2xl p-6 flex flex-col max-h-[90vh] border border-light-border dark:border-dark-border">
                <h1 className="text-2xl font-bold mb-4 text-center text-light-text dark:text-dark-text">
                    Terms of Use & Privacy Policy
                </h1>
                <div className="flex-1 overflow-y-auto pr-4 space-y-4 text-sm text-light-secondary-text dark:text-dark-secondary-text">
                    <p className="text-xs italic">Last updated: April 23, 2025</p>
                    <p className="font-semibold">Deep Thought AI, owned and operated by Atharvaa Ravichandran</p>
                    
                    <div>
                        <h2 className="font-bold text-light-text dark:text-dark-text mb-2">1. Introduction</h2>
                        <p>Welcome to Deep Thought AI — an intelligent conversational platform designed to provide information, creative assistance, and AI-powered insights. By using our services, you agree to these Terms of Use and our Privacy Policy. If you do not agree, please discontinue use immediately.</p>
                    </div>

                    <div>
                        <h2 className="font-bold text-light-text dark:text-dark-text mb-2">2. Who We Are</h2>
                        <p>Deep Thought AI is owned and operated by Atharvaa Ravichandran. We develop advanced artificial intelligence systems that help users communicate, learn, and explore ideas safely and effectively.</p>
                    </div>

                    <div>
                        <h2 className="font-bold text-light-text dark:text-dark-text mb-2">3. Use of Services</h2>
                        <p>You agree to use Deep Thought AI responsibly and in compliance with all applicable laws. You must not:</p>
                        <ul className="list-disc list-inside pl-4 mt-2 space-y-1">
                            <li>Use the service for illegal, harmful, or misleading purposes.</li>
                            <li>Attempt to reverse-engineer, copy, or exploit the AI model or system.</li>
                            <li>Use automated tools (bots, scrapers, etc.) to interact with the platform without permission.</li>
                            <li>Upload or share personal, confidential, or copyrighted content you don’t own.</li>
                        </ul>
                    </div>
                    
                    <div>
                        <h2 className="font-bold text-light-text dark:text-dark-text mb-2">4. Age Requirement</h2>
                        <p>Deep Thought AI is intended for users 13 years or older. If you are under 18, you must use the service under the supervision of a parent or guardian.</p>
                    </div>

                    <div>
                        <h2 className="font-bold text-light-text dark:text-dark-text mb-2">5. Your Content</h2>
                        <p>When you input text, prompts, or data into Deep Thought AI:</p>
                        <ul className="list-disc list-inside pl-4 mt-2 space-y-1">
                            <li>You retain ownership of your content.</li>
                            <li>You grant Deep Thought AI a limited license to process and use your input to provide and improve the service.</li>
                            <li>We may use anonymized and aggregated data for system improvement, analytics, or safety monitoring.</li>
                        </ul>
                    </div>

                    <div>
                        <h2 className="font-bold text-light-text dark:text-dark-text mb-2">6. Data Privacy</h2>
                        <p>Deep Thought AI respects your privacy. We collect limited information to operate and enhance the service, such as:</p>
                        <ul className="list-disc list-inside pl-4 mt-2 space-y-1">
                            <li>Device or browser data</li>
                            <li>Usage logs and timestamps</li>
                            <li>Chat content (for safety, debugging, and improvement)</li>
                        </ul>
                        <p className="mt-2">We do not sell, rent, or trade your personal data. We use encryption and modern security standards to protect user information.</p>
                    </div>

                    <div>
                        <h2 className="font-bold text-light-text dark:text-dark-text mb-2">7. AI Limitations</h2>
                        <p>The responses generated by Deep Thought AI are created using artificial intelligence and may not always be accurate, complete, or appropriate. You should not rely solely on AI outputs for medical, legal, financial, or professional advice. Use discretion and verify important information through reliable sources.</p>
                    </div>

                    <div>
                        <h2 className="font-bold text-light-text dark:text-dark-text mb-2">8. Service Changes</h2>
                        <p>We may update, suspend, or discontinue parts of the service at any time without prior notice. We are not liable for any loss, interruption, or data error caused by such updates.</p>
                    </div>

                    <div>
                        <h2 className="font-bold text-light-text dark:text-dark-text mb-2">9. Account & Security</h2>
                        <p>If you create an account, you are responsible for maintaining its confidentiality and all activity under it. We reserve the right to suspend or terminate accounts that violate our policies or misuse the platform.</p>
                    </div>

                    <div>
                        <h2 className="font-bold text-light-text dark:text-dark-text mb-2">10. Intellectual Property</h2>
                        <p>All platform content, design, code, and trademarks are the property of Deep Thought AI and Atharvaa Ravichandran. You may not copy, reproduce, or redistribute the system without written permission.</p>
                    </div>
                    
                    <div>
                        <h2 className="font-bold text-light-text dark:text-dark-text mb-2">11. Liability Disclaimer</h2>
                        <p>Deep Thought AI is provided “as is” without warranties of any kind. We are not responsible for damages arising from:</p>
                        <ul className="list-disc list-inside pl-4 mt-2 space-y-1">
                           <li>Inaccurate or inappropriate AI responses</li>
                           <li>Service downtime or data loss</li>
                           <li>Third-party integrations or misuse of content</li>
                        </ul>
                        <p className="mt-2">Your use of the platform is at your own risk.</p>
                    </div>

                    <div>
                        <h2 className="font-bold text-light-text dark:text-dark-text mb-2">12. Termination</h2>
                        <p>We may suspend or terminate your access to Deep Thought AI if you breach these Terms, misuse the service, or engage in harmful activity.</p>
                    </div>

                    <div>
                        <h2 className="font-bold text-light-text dark:text-dark-text mb-2">13. Changes to Terms</h2>
                        <p>We may update these Terms and our Privacy Policy periodically. Changes take effect immediately upon posting. Continued use after updates means you accept the revised terms.</p>
                    </div>

                    <div>
                        <h2 className="font-bold text-light-text dark:text-dark-text mb-2">14. Contact</h2>
                        <p>For questions, feedback, or concerns, contact:</p>
                        <p>📧 raviatharvaa2@gmail.com or aravi20@eq.edu.au</p>
                        <p>🌐 https://deepthoughtai.com</p>
                    </div>

                </div>
                <div className="mt-6 flex justify-end">
                    <button 
                        onClick={onAccept} 
                        className="w-full sm:w-auto px-6 py-3 bg-dark-accent text-white font-semibold rounded-lg shadow-md hover:bg-dark-accent-hover transition-colors"
                    >
                        Agree & Continue
                    </button>
                </div>
            </div>
        </div>
    );
};

export default TermsOfServiceModal;